### PR TITLE
Fix #205 : DTO attributes are ignored

### LINKED ISSUE #205: DTO attributes are ignored
### Describe the bug
`Edm.string` with` MaxLength` or `Nullable="false"` do not affect generated DTO.

#### Version of the Project affected
ODataConnectedService v0.12.x
VisualStudio Version v16.8.5
Microsoft.Odata.Client v7.8.2

#### To Reproduce
Create reference to OData service with an entity with a property of type `Edm.string` and a `MaxLength` or `Nullable="false"` property.

#### Expected behavior
Generated DTO should have a `MaxLength` = to the `MaxLength` in OData metadata and `Required`= to `!Nullable`.

#### Actual behavior
Generated DTO is the same, no matter what values `MaxLength `and `Nullable` have.

#### Additional context
Example metadata:
```
      <EntityType Name="dimension">
        <Key>
          <PropertyRef Name="dimensionCode" />
          <PropertyRef Name="code" />
        </Key>
        <Property Name="dimensionCode" Type="Edm.String" Nullable="false" MaxLength="20" />
        <Property Name="code" Type="Edm.String" Nullable="false" MaxLength="20" />
        <Property Name="name" Type="Edm.String" MaxLength="50" />
      </EntityType>
```

Generated DTO excerpt:

```
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>

```

### PR DESCRIPTION
**Pull request by unchase**
Fix #205

### CODE REVIEW

**Comment by marabooy** [comment]
@unchase I have merged #207

**Comment by unchase** [comment]
> @unchase I have merged #207

Thanks, I will try to finish the PR this week.

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

**Review by marabooy — APPROVED** [review]

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero rebased

**Comment by marabooy** [comment]
Thanks @unchase taking a look at this.

File: src/Templates/ODataT4CodeGenerator.cs [hunk 1]
```diff
@@ -1666,7 +1666,7 @@ internal string SingleSuffix
     internal abstract void WriteParameterNullCheckForStaticCreateMethod(string parameterName);
     internal abstract void WritePropertyValueAssignmentForStaticCreateMethod(string instanceName, string propertyName, string parameterName);
     internal abstract void WriteMethodEndForStaticCreateMethod(string instanceName);
-    internal abstract void WritePropertyForStructuredType(string propertyType, string originalPropertyName, string propertyName, string fixedPropertyName, string privatePropertyName, string propertyInitializationValue, string propertyAttribute, string propertyDescription, bool writeOnPropertyChanged, IDictionary<string, string> revisionAnnotations);
+    internal abstract void WritePropertyForStructuredType(string propertyType, string originalPropertyName, string propertyName, string fixedPropertyName, string privatePropertyName, string propertyInitializationValue, string propertyAttribute, string propertyDescription, int? propertyMaxLength, bool writeOnPropertyChanged, bool isNullable, IDictionary<string, string> revisionAnnotations);
```
Comment (habbes) [inline src/Templates/ODataT4CodeGenerator.cs:1669]: I don't think adding more and more parameters to this method for every new attributes we want to support is a sustainable approach. In my view we should have a class where all these annotations could be stored as properties, and then we just pass a single object that encapsulate all attributes. That way whenever we want to support a new attribute, we just add a property to the class and only update the methods where that attribute is relevant, instead of adding new arguments to so many places.

**Review by habbes — APPROVED** [review]

**Comment by habbes** [comment]
@unchase do you have any test case for the `StringLengthAttribute`? I've seen some for the `RequiredAttribute`

File: src/Templates/ODataT4CodeGenerator.cs (hunk 1 above)
Comment (unchase) [reply src/Templates/ODataT4CodeGenerator.cs:1669]: Agree with you. I also thought about it.

**Comment by unchase** [comment]
> @unchase do you have any test case for the `StringLengthAttribute`? I've seen some for the `RequiredAttribute`

I'll add them tonight.

File: test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs [hunk 2]
```diff
@@ -591,9 +591,9 @@ internal override void WriteMethodEndForStaticCreateMethod(string instanceName)
...
+            internal override void WritePropertyForStructuredType(string propertyType, string originalPropertyName, string propertyName, string fixedPropertyName, string privatePropertyName, string propertyInitializationValue, string propertyAttribute, string propertyDescription, int? propertyMaxLength, bool writeOnPropertyChanged, bool isNullable, IDictionary<string, string> revisionAnnotations)
             {
-                this.CalledActions.Add("WritePropertyForStructuredType(" + propertyType + ", " + originalPropertyName + ", " + propertyName + ", " + fixedPropertyName + ", " + privatePropertyName + ", " + propertyInitializationValue + ", " + propertyAttribute + ", " + writeOnPropertyChanged + ", " + revisionAnnotations + ")");
+                this.CalledActions.Add("WritePropertyForStructuredType(" + propertyType + ", " + originalPropertyName + ", " + propertyName + ", " + fixedPropertyName + ", " + privatePropertyName + ", " + propertyInitializationValue + ", " + propertyAttribute + ", " + propertyMaxLength + ", " + writeOnPropertyChanged + ", " + isNullable + ", " + revisionAnnotations + ")");
```
Comment (wandeg) [inline test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs:596]: Any reason not to use [String.Join](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=net-5.0#System_String_Join_System_String_System_String___) ?

Comment (unchase) [reply test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs:596]: We can use `PropertyOptions` class instead of it.

Comment (unchase) [reply test/ODataConnectedService.Tests/Templates/ODataClientTemplateUnitTests.cs]: Added

File: src/Templates/ODataT4CodeGenerator.cs (hunk 1 above)
Comment (unchase) [reply src/Templates/ODataT4CodeGenerator.cs]: Fixed

**Review by wandeg — APPROVED** [review]

File: src/Templates/ODataT4CodeGenerator.cs [hunk 3]
```diff
@@ -5218,7 +5296,7 @@ internal override void WriteEnumFlags()
 
     internal override void WriteSummaryCommentForEnumType(string enumName, string description)
     {
-        WriteDescriptionSummary(string.IsNullOrWhiteSpace(description) ? $"There are no comments for {enumName} in the schema." : description);
+        WriteDescriptionSummary(string.IsNullOrWhiteSpace(description) ? $"There are no comments for {enumName} in the schema." : description, true);
```
Comment (KenitoInc) [inline src/Templates/ODataT4CodeGenerator.cs:5299]: Why did we make `isClass = true`?

File: src/Templates/ODataT4CodeGenerator.cs [hunk 4]
```diff
@@ -7333,7 +7450,7 @@ internal override void WriteEnumFlags()
...
```
Comment (KenitoInc) [inline src/Templates/ODataT4CodeGenerator.cs:7453]: Same comment as above regarding `isClass = true`.

**Review by KenitoInc — APPROVED** [review]

**Comment by KenitoInc** [comment]
Thanks for this PR @unchase
