### PR TITLE
Fix #191 : Tool generates non-compilable code

### LINKED ISSUE #191: Tool generates non-compilable code
### Describe the bug
I created a specific model, with 2 types with the same name, but different namespaces
And both of those Types used in another one, as Collection Item properties.
ConnectedService provide non-compilable code when using both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.

#### Version of the Project affected
ODataConnectedService v0.11.1.0
VisualStudio Version v16.5.4

#### To Reproduce
1. Example repository with model https://github.com/pil0t/ExampleForODataConnectedServices
2. Run the application from above
3. Use https://localhost:5001/v1/$metadata  or (https://gist.github.com/pil0t/ebecb6c6aa1a8695e065ecfbdbb395d4)
4. Use metadata from above for generating new ConnectedServiceReference using both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.
5. Generation successful
6. Compile

#### Expected behavior
Compile without problem

#### Actual behavior
Getting compile errors: CS0234

#### Screenshots
Added 1 min recording for convenience 
odataCompileError

#### Additional context
This not happens without both `GenerateMultipleFiles` and `EnableEntityAndPropertyTracking` options at the same time.

### PR DESCRIPTION
**Pull request by unchase**
Fix #191.
Added ability to show full name for schema types in `Schema Types Selection` page.

Example:

issue191

for metadata:

```xml
<?xml version="1.0" standalone="yes" ?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Namespace1" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="TestType">
        <Key>
          <PropertyRef Name="KeyProp" />
        </Key>
        <Property Name="KeyProp" Type="Edm.Int32" Nullable="false" />
        <Property Name="ValueProp" Type="Edm.String" Nullable="false" />
      </EntityType>
    </Schema>
    <Schema Namespace="Namespace2" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="TestType">
        <Key>
          <PropertyRef Name="KeyProp1" />
        </Key>
        <Property Name="KeyProp1" Type="Edm.Int32" Nullable="false" />
        <Property Name="ValueProp2" Type="Edm.String" Nullable="false" />
      </EntityType>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

---

Added the tests below:

To **ODataT4CodeGeneratorTests:**

- [x] `CodeGenSameNamedEntityEdmxMultipleFiles`.

To **BoolToVisibilityConverterTests:**

- [x] `Convert_ShouldReturnVisible_ForFalseValue_WithTrueParameter`;
- [x] `Convert_ShouldReturnCollapsed_ForTrueValue_WithTrueParameter`.

To **ODataClientTemplateUnitTest:**

- [x] `GetFileNameForMultipleFilesGenerationForSameNamedTypesShouldReturnsFileNamesWithNamespaces`;
- [x] `GetFileNameForMultipleFilesGenerationForSimpleEdmxShouldReturnsFileNamesWithoutNamespaces`.

### CODE REVIEW

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

**Review by marabooy — APPROVED** [review]

**Review by KenitoInc — COMMENTED** [review]
So we are providing an option to add `Namespace` to the `Type`? We are not automatically adding a `Namespace` whenever we have a conflict

**Comment by unchase** [comment]
> So we are providing an option to add `Namespace` to the `Type`? We are not automatically adding a `Namespace` whenever we have a conflict

Anyway we should resolve conflicts in file names when generates multiple files for same named types. I think that we should not to give possibility to disable this option to users.

**Review by KenitoInc — APPROVED** [review]
LGTM

File: src/Converters/BoolToVisibilityConverter.cs [hunk 1]
```diff
@@ -19,7 +19,14 @@ public object Convert(object value, Type targetType, object parameter, CultureIn
             if (targetType == typeof(Visibility))
             {
                 if (value is bool boolValue)
+                {
+                    if (parameter is string isInversed && isInversed.Equals("true", StringComparison.OrdinalIgnoreCase))
```
Comment (gathogojr) [inline src/Converters/BoolToVisibilityConverter.cs:23]: @unchase 
nit: `isInversed` as a variable name sounds best suited for a boolean

File: src/Templates/ODataT4CodeGenerator.cs [hunk 2]
```diff
@@ -1855,7 +1874,7 @@ internal void WriteNamespace(string fullNamespace)
         {
             if(context.GenerateMultipleFiles)
             {
-                context.MultipleFilesManager.StartNewFile($"ExtensionMethods{(this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs")}",false);
+                context.MultipleFilesManager.StartNewFile($"{(this.context.NamespacesInModel.Length > 1 ? $"{fullNamespace}." : string.Empty)}ExtensionMethods{(this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs")}", false);
```
Comment (gathogojr) [inline src/Templates/ODataT4CodeGenerator.cs:1877]:
```suggestion
                var ns = this.context.NamespacesInModel.Length > 1 ? $"{fullNamespace}." : string.Empty;
                var fileExtension = this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs";
                context.MultipleFilesManager.StartNewFile($"{ns}ExtensionMethods{fileExtension}", false);
```
@unchase For readability

File: src/Templates/ODataT4CodeGenerator.cs [hunk 3]
```diff
@@ -1802,7 +1809,13 @@ internal void WriteNamespace(string fullNamespace)
...
                     if(context.GenerateMultipleFiles)
                     {
-                        context.MultipleFilesManager.StartNewFile($"{complexType.Name}{(this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs")}",false);
+                        string fileName = complexType.Name;
+                        if (schemaElementsInModel.Count(e => e.Name.Equals(complexType.Name)) > 1)
+                        {
+                            fileName = complexType.FullName();
+                        }
+
+                        context.MultipleFilesManager.StartNewFile($"{fileName}{(this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs")}", false);
```
Comment (gathogojr) [inline src/Templates/ODataT4CodeGenerator.cs:1818]:
```suggestion
                        var fileExtension = this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs";
                        context.MultipleFilesManager.StartNewFile($"{fileName}{fileExtension}", false);
```
@unchase For readability

Comment (gathogojr) [inline src/Templates/ODataT4CodeGenerator.cs:1818]: Or maybe we should have a helper method that returns the file extension since `this.context.TargetLanguage == LanguageOption.VB ? ".vb" : ".cs"` is repeated quite a few times...

File: src/Templates/ODataT4CodeGenerator.cs [hunk 4]
```diff
@@ -1772,24 +1773,30 @@ internal void WriteNamespace(string fullNamespace)
...
-                    }
+                if (this.context.ExcludedSchemaTypes != null && this.context.ExcludedSchemaTypes.Contains(enumType.FullName()))
+                {
+                    continue;
+                }
 
-                    if(context.GenerateMultipleFiles)
+                if(context.GenerateMultipleFiles)
+                {
+                    string fileName = enumType.Name;
```
Comment (gathogojr) [inline src/Templates/ODataT4CodeGenerator.cs:1783]: @unchase The four lines starting here are repeated quite a few times across the file. A helper method would help us avoid code duplication I think?

File: test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs [hunk 5]
```diff
@@ -190,6 +190,31 @@ public void CodeGenSimpleEdmxMultipleFiles()
             Assert.AreEqual(expectedExtensionMethods, actualExtenisonMethods);
         }
 
+        [TestMethod]
+        public void CodeGenSameNamedEntityEdmxMultipleFiles()
```
Comment (gathogojr) [inline test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs:194]: @unchase We could reduce code duplication in this test by use of parameterized tests supported by Xunit.
```csharp
[Theory]
[InlineData("SameNamedEntityMultipleNamespace1TestType.cs", "Namespace1.TestType.cs")]
//...etc
public void CodeGenSameNamedEntityEdmxMultipleFiles(string param1, string param2)
{
    // ...
}
```

File: src/Templates/ODataT4CodeGenerator.cs (hunk 4 above)
Comment (unchase) [reply src/Templates/ODataT4CodeGenerator.cs:1783]: Agree

File: src/Templates/ODataT4CodeGenerator.cs (hunk 3 above)
Comment (unchase) [reply src/Templates/ODataT4CodeGenerator.cs:1818]: I think should put it into the same helper method.

File: test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs (hunk 5 above)
Comment (unchase) [reply test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs:194]: I think that we can refactor the hole `ODataT4CodeGeneratorTests.cs` file using Xunit in the next PR.

File: src/Converters/BoolToVisibilityConverter.cs (hunk 1 above)
Comment (unchase) [reply src/Converters/BoolToVisibilityConverter.cs]: Fixed in https://github.com/OData/ODataConnectedService/pull/203/commits/ad35066a3f8ec1c51e89dc42eea4830c1098f099

**Review by gathogojr — APPROVED** [review]
